### ISSUE TITLE
Lege cloetjes uit database verwijderen

### ISSUE THREAD

**Issue by TKStrijker** [Cleopatra-cyc0/telegram-derposbot#3]
Alle "lege" cloetjes moeten uit de database gehaald worden.

Graag eerst een kopie van de database maken, daar dan de lege cloetjes uithalen en dan (als je niet alles hebt verneukt) de productie database vervangen met je aangepaste kopie.

**Comment by mees-** [comment]
Je wil in plaats van een migratie een hele database vervangen?

**Comment by mees-** [comment]
done:
```sql
delete from quote where trim(quote.text) = '';
```
